### ISSUE TITLE
Dialogue editor formatting crash

### ISSUE THREAD

**Issue by chasminimus** [ByteNybbler/MNIKEditor#2]
This one is a little weird because I can't always reproduce it, but:
1. open the dialogue editor for the first time after opening the program
2. apply some kind of formatting to part of the text
3. apply some kind of formatting to the formatting block _right before_ the part you just formatted in 2
4. crash! (MAV)

I think it ONLY happens on the first usage of the dialogue editor but I could be wrong.

**Comment by ByteNybbler** [comment]
This bug has been fixed in the 8/31/22 build.
